// lib/data.ts

export const specialists = [
    {
      id: "1",
      name: "Dr. Ana Reptiliana",
      title: "Veterinária Especialista em Répteis",
      rating: 4.9,
      reviews: 127,
      price: "R$ 150",
      location: "Vila Madalena, SP",
      experience: "8 anos",
      education: "Veterinária - USP",
      specialties: ["Répteis", "Anfíbios", "Quelônios"],
      image: "/woman-smiling-dog.png",
      badges: ["Veterinária", "Certificado IBAMA", "Emergência 24h", "Cirurgia"],
      bio: "Especialista em medicina veterinária de animais exóticos com foco em répteis e anfíbios. Formada pela USP com pós-graduação em medicina de animais silvestres. Atua há 8 anos no cuidado especializado de animais exóticos.",
      certifications: [
        "Medicina Veterinária - USP (2016)",
        "Pós-graduação em Animais Silvestres - ANCLIVEPA (2018)",
        "Certificação IBAMA para Fauna Silvestre (2019)",
        "Curso Avançado em Cirurgia de Répteis - ARAV (2021)",
      ],
      plans: [
        { name: "Plano Básico", type: "weekly", price: 120, originalPrice: 150, discount: "20%", description: "1 visita por semana", features: ["Cuidado domiciliar", "Relatório semanal", "Suporte via WhatsApp"]},
        { name: "Plano Completo", type: "monthly", price: 400, originalPrice: 600, discount: "33%", description: "4 visitas por mês + consulta", features: ["4 visitas domiciliares", "1 consulta veterinária", "Relatórios detalhados", "Suporte 24h", "Desconto em emergências"]},
      ],
      stats: { totalAnimals: 89, emergenciesHandled: 23, successRate: 98, responseTime: "< 2h" },
    },
    {
      id: "2",
      name: "Carlos Primata",
      title: "Biólogo Especialista em Primatas",
      rating: 4.8,
      reviews: 89,
      price: "R$ 200",
      location: "Copacabana, RJ",
      experience: "12 anos",
      education: "Biólogo - UFRJ",
      specialties: ["Primatas", "Mamíferos Exóticos"],
      image: "/man-with-golden-retriever.jpg",
      badges: ["Biólogo", "Manejo Primatas", "Comportamento Animal"],
      bio: "Biólogo com vasta experiência em comportamento e manejo de primatas. Trabalhou em santuários e projetos de conservação, garantindo o bem-estar de diversas espécies.",
      certifications: ["Ciências Biológicas - UFRJ (2010)", "Mestrado em Comportamento Animal - UERJ (2012)"],
      plans: [{ name: "Plano Acompanhamento", type: "weekly", price: 180, description: "1 visita semanal", features: ["Enriquecimento ambiental", "Relatório comportamental", "Suporte"] }],
      stats: { totalAnimals: 45, emergenciesHandled: 10, successRate: 99, responseTime: "< 4h" },
    },
    {
      id: "3",
      name: "Dra. Maria Aviária",
      title: "Veterinária Especialista em Aves",
      rating: 5.0,
      reviews: 203,
      price: "R$ 180",
      location: "Bela Vista, SP",
      experience: "10 anos",
      education: "Veterinária - FMVZ",
      specialties: ["Aves Exóticas", "Psitacídeos"],
      image: "/woman-walking-small-dogs.jpg",
      badges: ["Especialista Aves", "Cirurgia", "Nutrição Aviária"],
      bio: "Apaixonada por aves, Dra. Maria é referência em cirurgia e nutrição de psitacídeos e outras aves raras, com mais de uma década de experiência clínica.",
      certifications: ["Medicina Veterinária - FMVZ (2012)", "Especialização em Aves - ANCLIVEPA (2015)"],
      plans: [{ name: "Cuidado Aviário Mensal", type: "monthly", price: 550, description: "4 visitas + consulta", features: ["Cuidado completo", "Aparação de penas e unhas", "Orientação nutricional"] }],
      stats: { totalAnimals: 250, emergenciesHandled: 50, successRate: 99, responseTime: "< 1h" },
    },
    {
      id: "4",
      name: "Dr. Lucas Ferreira",
      title: "Veterinário Especialista em Serpentes",
      rating: 4.9,
      reviews: 95,
      price: "R$ 160",
      location: "Savassi, Belo Horizonte",
      experience: "7 anos",
      education: "Veterinária - UFMG",
      specialties: ["Répteis", "Serpentes"],
      image: "/professional-veterinarian-man.jpg",
      badges: ["Veterinário", "Manejo de Peçonhentos"],
      bio: "Com foco em ofídios, Dr. Lucas é um dos poucos especialistas em manejo de serpentes peçonhentas e constritoras, atuando em Belo Horizonte e região.",
      certifications: ["Medicina Veterinária - UFMG (2017)"],
      plans: [{ name: "Plano Serpentário", type: "monthly", price: 450, description: "2 visitas mensais", features: ["Verificação de habitat", "Acompanhamento de ecdise", "Telemedicina"] }],
      stats: { totalAnimals: 120, emergenciesHandled: 30, successRate: 97, responseTime: "< 3h" },
    },
    {
      id: "5",
      name: "Dra. Juliana Alves",
      title: "Bióloga Especialista em Aracnídeos",
      rating: 4.8,
      reviews: 78,
      price: "R$ 175",
      location: "Buritis, Belo Horizonte",
      experience: "9 anos",
      education: "Bióloga - PUC Minas",
      specialties: ["Anfíbios", "Aracnídeos"],
      image: "/professional-veterinarian-woman-smiling.jpg",
      badges: ["Bióloga", "Especialista em Anfíbios"],
      bio: "Dra. Juliana é bióloga e especialista no cuidado de anfíbios e aracnídeos, oferecendo consultoria sobre habitat, alimentação e bem-estar para criadores.",
      certifications: ["Ciências Biológicas - PUC Minas (2014)"],
      plans: [{ name: "Consultoria Habitat", type: "single", price: 250, description: "Visita única para montagem", features: ["Análise de terrário", "Indicação de equipamentos", "Guia de cuidados"] }],
      stats: { totalAnimals: 300, emergenciesHandled: 5, successRate: 100, responseTime: "< 24h" },
    },
    {
      id: "6",
      name: "Clínica ExoticPet BH",
      title: "Clínica Especializada 24h",
      rating: 5.0,
      reviews: 150,
      price: "R$ 220",
      location: "Centro, Belo Horizonte",
      experience: "15 anos",
      education: "Equipe Multidisciplinar",
      specialties: ["Aves Raras", "Mamíferos"],
      image: "/professional-veterinarian-woman.jpg",
      badges: ["Clínica 24h", "Cirurgia Especializada", "UTI"],
      bio: "A ExoticPet BH é a principal clínica de emergência para animais exóticos em Minas Gerais, com uma equipe completa e equipamentos de ponta para cirurgias e internação.",
      certifications: ["CRMV-MG Ativo", "Selo de Qualidade Veterinária"],
      plans: [{ name: "Plano de Saúde Anual", type: "yearly", price: 1200, description: "Cobertura completa", features: ["Consultas ilimitadas", "Desconto em exames", "Prioridade em emergências"] }],
      stats: { totalAnimals: 1500, emergenciesHandled: 400, successRate: 95, responseTime: "imediato" },
    },
  ];